// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'timoncode/models/song.dart';
import 'timoncode/models/tag.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 9010798967777340560),
      name: 'Song',
      lastPropertyId: const IdUid(7, 4633956051513000642),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7159351169199739191),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3115723590380257770),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8594253787416493472),
            name: 'artist',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 614895528964824454),
            name: 'spotifyId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(1, 3324877264777455464)),
        ModelProperty(
            id: const IdUid(5, 347302859567081836),
            name: 'duration',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2913082945644414994),
            name: 'dateAdded',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4633956051513000642),
            name: 'releaseDate',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(1, 2933435051223473136),
            name: 'tags',
            targetId: const IdUid(2, 3379074201238304732))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 3379074201238304732),
      name: 'Tag',
      lastPropertyId: const IdUid(5, 8200168161526390469),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(2, 190164107148731585),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(3, 4695901502359810162),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1302384689009912107),
            name: 'colourId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8200168161526390469),
            name: 'userDefined',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(name: 'songs', srcEntity: 'Song', srcField: '')
      ])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 3379074201238304732),
      lastIndexId: const IdUid(1, 3324877264777455464),
      lastRelationId: const IdUid(1, 2933435051223473136),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [5489380764927646302],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Song: EntityDefinition<Song>(
        model: _entities[0],
        toOneRelations: (Song object) => [],
        toManyRelations: (Song object) =>
            {RelInfo<Song>.toMany(1, object.id): object.tags},
        getId: (Song object) => object.id,
        setId: (Song object, int id) {
          object.id = id;
        },
        objectToFB: (Song object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final artistOffset = fbb.writeString(object.artist);
          final spotifyIdOffset = fbb.writeString(object.spotifyId);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, artistOffset);
          fbb.addOffset(3, spotifyIdOffset);
          fbb.addInt64(4, object.duration);
          fbb.addInt64(5, object.dateAdded.millisecondsSinceEpoch);
          fbb.addInt64(6, object.releaseDate.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Song(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              artist: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              spotifyId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              duration:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0))
            ..dateAdded = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0))
            ..releaseDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          InternalToManyAccess.setRelInfo<Song>(
              object.tags, store, RelInfo<Song>.toMany(1, object.id));
          return object;
        }),
    Tag: EntityDefinition<Tag>(
        model: _entities[1],
        toOneRelations: (Tag object) => [],
        toManyRelations: (Tag object) =>
            {RelInfo<Song>.toManyBacklink(1, object.id): object.songs},
        getId: (Tag object) => object.id,
        setId: (Tag object, int id) {
          object.id = id;
        },
        objectToFB: (Tag object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(6);
          fbb.addInt64(1, object.id);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(3, object.colourId);
          fbb.addBool(4, object.userDefined);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Tag(
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              colourId:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              userDefined: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 12, false));
          InternalToManyAccess.setRelInfo<Tag>(
              object.songs, store, RelInfo<Song>.toManyBacklink(1, object.id));
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Song] entity fields to define ObjectBox queries.
class Song_ {
  /// see [Song.id]
  static final id = QueryIntegerProperty<Song>(_entities[0].properties[0]);

  /// see [Song.name]
  static final name = QueryStringProperty<Song>(_entities[0].properties[1]);

  /// see [Song.artist]
  static final artist = QueryStringProperty<Song>(_entities[0].properties[2]);

  /// see [Song.spotifyId]
  static final spotifyId =
      QueryStringProperty<Song>(_entities[0].properties[3]);

  /// see [Song.duration]
  static final duration =
      QueryIntegerProperty<Song>(_entities[0].properties[4]);

  /// see [Song.dateAdded]
  static final dateAdded =
      QueryIntegerProperty<Song>(_entities[0].properties[5]);

  /// see [Song.releaseDate]
  static final releaseDate =
      QueryIntegerProperty<Song>(_entities[0].properties[6]);

  /// see [Song.tags]
  static final tags = QueryRelationToMany<Song, Tag>(_entities[0].relations[0]);
}

/// [Tag] entity fields to define ObjectBox queries.
class Tag_ {
  /// see [Tag.id]
  static final id = QueryIntegerProperty<Tag>(_entities[1].properties[0]);

  /// see [Tag.name]
  static final name = QueryStringProperty<Tag>(_entities[1].properties[1]);

  /// see [Tag.colourId]
  static final colourId = QueryIntegerProperty<Tag>(_entities[1].properties[2]);

  /// see [Tag.userDefined]
  static final userDefined =
      QueryBooleanProperty<Tag>(_entities[1].properties[3]);
}
